name: run-tests

on: [push, pull_request]
env:
    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    DB_DATABASE: unit_tests
jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [7.4]
                laravel: [8.*]
                dependency-version: [prefer-stable]
                include:
                    -   laravel: 8.*
                        testbench: 6.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Get git commit data 1
                uses: rlespinasse/git-commit-data-action@1.1.0

            -   name: Get git commit data 2
                run: |
                    echo "AUTHOR_FIRSTNAME=$(echo $GIT_COMMIT_AUTHOR_NAME | head -n1 | cut -d ' ' -f1)" >> $GITHUB_ENV
                    echo "GIT_SHORT_HASH=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
                    echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

            -   name: Set up MySQL
                run: |
                    sudo /etc/init.d/mysql start
                    mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -uroot -proot

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer config --global --auth http-basic.repo.packagist.com egbertwietses ${{secrets.DAALDER}}
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -   name: Setup Problem Matches
                run: |
                    echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                    echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Execute tests
                run: vendor/bin/phpunit

            -   name: Post failure status to Slack
                run: |
                    echo "https://github.com/Daalder/job-central/commit/$GITHUB_SHA"
                    echo "$GITHUB_HEAD_REF"
                    echo "@$AUTHOR_FIRSTNAME"
                    curl -X POST -H "Authorization: Bearer $BEARER_TOKEN" "$BASE_URL?channel=$CHANNEL&link_names=true&pretty=1" \
                        --data-urlencode "text=:no_entry: Job-Central tests failed for $(echo '`'; echo $GIT_BRANCH; echo '`') @ $(echo '`')<$(echo https://github.com/Daalder/job-central/commit/$GITHUB_SHA)|$GIT_SHORT_HASH>$(echo '`') by @$AUTHOR_FIRSTNAME"
                env:
                    BEARER_TOKEN: ${{ secrets.SLACK_BEARER_TOKEN }}
                    BASE_URL: https://slack.com/api/chat.postMessage
                    CHANNEL: programmers
                if: always() # Pick up events when the job fails or is canceled
